// Mémoire — Gift Catalogue Data
// These are showcased as inspiration items; all orders are by enquiry only.

const GIFTS_DATA = [
  {
    id: 'g1',
    name: 'Eternal Oak Frame',
    category: 'Memory Frames',
    cat: 'frames',
    occasions: ['anniversary', 'wedding', 'all'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80',
    description: 'Hand-engraved solid oak frame with personalised date, names, and coordinates. For the photograph that has been waiting for a worthy home.',
    badge: 'Bestseller',
    whatsappMsg: "Hello! I'm interested in the Eternal Oak Frame. Can we discuss personalization?",
  },
  {
    id: 'g2',
    name: 'Walnut Memory Box',
    category: 'Keepsake Boxes',
    cat: 'boxes',
    occasions: ['anniversary', 'wedding', 'birthday', 'all'],
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80',
    description: 'A hand-crafted walnut box with brass hinges and a debossed monogram lid — for the letters, tokens, and trinkets too important to leave in a drawer.',
    badge: null,
    whatsappMsg: "Hello! I'm interested in the Walnut Memory Box. Can you share more details?",
  },
  {
    id: 'g3',
    name: 'Night Sky Map',
    category: 'Personalized Art',
    cat: 'art',
    occasions: ['birthday', 'anniversary', 'newborn', 'all'],
    image: 'https://images.unsplash.com/photo-1614094082869-cd4e4b2905c7?auto=format&fit=crop&w=600&q=80',
    description: 'The exact constellation of stars visible from any location on any date — printed on archival cotton paper and framed in hand-stained black oak.',
    badge: 'Popular',
    whatsappMsg: "Hello! I'd like a Night Sky Map for a special date. Can we talk?",
  },
  {
    id: 'g4',
    name: 'Linen Memory Journal',
    category: 'Keepsake Boxes',
    cat: 'boxes',
    occasions: ['friendship', 'birthday', 'all'],
    image: 'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?auto=format&fit=crop&w=600&q=80',
    description: 'A hand-bound linen journal with debossed initials on the cover. Unlined pages for drawings, pressed flowers, tickets, and the memories still being made.',
    badge: null,
    whatsappMsg: "Hello! I'm interested in the Linen Memory Journal.",
  },
  {
    id: 'g5',
    name: 'Brass City Map',
    category: 'Personalized Art',
    cat: 'art',
    occasions: ['corporate', 'wedding', 'anniversary', 'all'],
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=600&q=80',
    description: 'The streets of any city — the city where you met, where you married, where you built something — etched into a hand-polished brass panel.',
    badge: 'Signature',
    whatsappMsg: "Hello! I'd like a Brass City Map engraved. Can we discuss the details?",
  },
  {
    id: 'g6',
    name: 'Heritage Gift Set',
    category: 'Gift Sets',
    cat: 'sets',
    occasions: ['corporate', 'wedding', 'anniversary', 'all'],
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=600&q=80',
    description: 'A curated collection: engraved frame, walnut box, and linen journal — wrapped in natural linen and tied with gold ribbon. For moments that deserve the full gesture.',
    badge: 'New',
    whatsappMsg: "Hello! I'm interested in the Heritage Gift Set. Can you share pricing?",
  },
  {
    id: 'g7',
    name: 'Birth Announcement Frame',
    category: 'Memory Frames',
    cat: 'frames',
    occasions: ['newborn', 'all'],
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=600&q=80',
    description: "Name, weight, height, date, and time — everything about the moment they arrived, hand-engraved into warm teak. A first portrait they'll treasure forever.",
    badge: null,
    whatsappMsg: "Hello! I'd like a Birth Announcement Frame for a new baby.",
  },
  {
    id: 'g8',
    name: 'Memorial Keepsake Box',
    category: 'Keepsake Boxes',
    cat: 'boxes',
    occasions: ['memorial', 'all'],
    image: 'https://images.unsplash.com/photo-1473188588951-666fce8e7c68?auto=format&fit=crop&w=600&q=80',
    description: 'A gentle, lasting piece for holding the memory of someone who mattered — their photograph, their handwriting, their favourite things. Made with quiet reverence.',
    badge: null,
    whatsappMsg: "Hello, I'd like to enquire about a memorial keepsake box.",
  },
  {
    id: 'g9',
    name: 'Personalised Portrait',
    category: 'Personalized Art',
    cat: 'art',
    occasions: ['birthday', 'anniversary', 'friendship', 'all'],
    image: 'https://images.unsplash.com/photo-1607344645866-009c320b63e0?auto=format&fit=crop&w=600&q=80',
    description: 'A hand-drawn portrait from your photograph — rendered in pencil or watercolour by our in-house illustrator. Framed and ready to give.',
    badge: null,
    whatsappMsg: "Hello! I'd like to commission a personalised portrait. Can we discuss it?",
  },
  {
    id: 'g10',
    name: 'Corporate Gift Collection',
    category: 'Corporate',
    cat: 'corporate',
    occasions: ['corporate', 'all'],
    image: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=600&q=80',
    description: 'Branded, bespoke, and beautifully made for corporate gifting. Minimum 25 pieces. Each delivered individually wrapped with a personalised message.',
    badge: 'Corporate',
    whatsappMsg: "Hello! I'd like to enquire about corporate gifting with Mémoire.",
  },
];
